from discord_components import SelectOption

DECKS = {
    'Basic Playing Cards': {
        'Ace of Spades': '',
        '2 of Spades': '',
        '3 of Spades': '',
        '4 of Spades': '',
        '5 of Spades': '',
        '6 of Spades': '',
        '7 of Spades': '',
        '8 of Spades': '',
        '9 of Spades': '',
        '10 of Spades': '',
        'Jack of Spades': '',
        'Queen of Spades': '',
        'King of Spades': '',
        'Ace of Hearts': '',
        '2 of Hearts': '',
        '3 of Hearts': '',
        '4 of Hearts': '',
        '5 of Hearts': '',
        '6 of Hearts': '',
        '7 of Hearts': '',
        '8 of Hearts': '',
        '9 of Hearts': '',
        '10 of Hearts': '',
        'Jack of Hearts': '',
        'Queen of Hearts': '',
        'King of Hearts': '',
        'Ace of Diamons': '',
        '2 of Diamonds': '',
        '3 of Diamonds': '',
        '4 of Diamonds': '',
        '5 of Diamonds': '',
        '6 of Diamonds': '',
        '7 of Diamonds': '',
        '8 of Diamonds': '',
        '9 of Diamonds': '',
        '10 of Diamonds': '',
        'Jack of Diamonds': '',
        'Queen of Diamonds': '',
        'King of Diamonds': '',
        'Ace of Clubs': '',
        '2 of Clubs': '',
        '3 of Clubs': '',
        '4 of Clubs': '',
        '5 of Clubs': '',
        '6 of Clubs': '',
        '7 of Clubs': '',
        '8 of Clubs': '',
        '9 of Clubs': '',
        '10 of Clubs': '',
        'Jack of Clubs': '',
        'Queen of Clubs': '',
        'King of Clubs': ''
        },   
    'Cyberpunk Tarot': {
        'The Fool': 'https://static.wikia.nocookie.net/cyberpunk/images/b/b1/TarotCard_01_TheFool.png/revision/latest?cb=20210103215616',
        'The Magician': 'https://static.wikia.nocookie.net/cyberpunk/images/d/d6/TarotCard_02_TheMagician.png/revision/latest?cb=20210103215747',
        'The High Priestess': 'https://static.wikia.nocookie.net/cyberpunk/images/b/bf/TarotCard_03_TheHighPriestess.png/revision/latest?cb=20210103215846',
        'The Empress': 'https://static.wikia.nocookie.net/cyberpunk/images/1/1d/TarotCard_04_TheEmpress.png/revision/latest?cb=20210103220157',
        'The Emperor': 'https://static.wikia.nocookie.net/cyberpunk/images/d/df/TarotCard_05_TheEmperor.png/revision/latest?cb=20210103220447',
        'The Hierophant': 'https://static.wikia.nocookie.net/cyberpunk/images/d/d2/TarotCard_06_TheHierophant.png/revision/latest?cb=20210103220542',
        'The Lovers': 'https://static.wikia.nocookie.net/cyberpunk/images/f/f3/TarotCard_07_TheLovers.png/revision/latest?cb=20210103220610',
        'The Chariot': 'https://static.wikia.nocookie.net/cyberpunk/images/c/cb/TarotCard_08_TheChariot.png/revision/latest?cb=20210103220714',
        'Strength': 'https://static.wikia.nocookie.net/cyberpunk/images/8/88/TarotCard_09_Strength.png/revision/latest?cb=20210103220829',
        'The Hermit': 'https://static.wikia.nocookie.net/cyberpunk/images/4/4f/TarotCard_10_TheHermit.png/revision/latest?cb=20210103220946',
        'Wheel of Fortune': 'https://static.wikia.nocookie.net/cyberpunk/images/0/01/TarotCard_11_WheelOfFortune.png/revision/latest?cb=20210103221204',
        'Justice': 'https://static.wikia.nocookie.net/cyberpunk/images/4/4f/TarotCard_12_Justice.png/revision/latest?cb=20210103221316',
        'The Hanged Man': 'https://static.wikia.nocookie.net/cyberpunk/images/0/0e/TarotCard_13_TheHangedMan.png/revision/latest?cb=20210103221527',
        'Death': 'https://static.wikia.nocookie.net/cyberpunk/images/8/8e/TarotCard_14_Death.png/revision/latest?cb=20210103221556',
        'Temperance': 'https://static.wikia.nocookie.net/cyberpunk/images/2/21/TarotCard_15_Temperance.png/revision/latest?cb=20210103221722',
        'The Devil': 'https://static.wikia.nocookie.net/cyberpunk/images/1/11/TarotCard_16_TheDevil.png/revision/latest?cb=20210103221749',
        'The Tower': 'https://static.wikia.nocookie.net/cyberpunk/images/b/b6/TarotCard_17_TheTower.png/revision/latest?cb=20210103221813',
        'The Star': 'https://static.wikia.nocookie.net/cyberpunk/images/5/59/TarotCard_18_TheStar.png/revision/latest?cb=20210103221837',
        'The Moon': 'https://static.wikia.nocookie.net/cyberpunk/images/1/15/TarotCard_19_TheMoon.png/revision/latest?cb=20210103221900',
        'The Sun': 'https://static.wikia.nocookie.net/cyberpunk/images/d/d1/TarotCard_20_TheSun.png/revision/latest?cb=20210103221943',
        'Judgment': 'https://static.wikia.nocookie.net/cyberpunk/images/1/14/TarotCard_21_Judgement.png/revision/latest?cb=20210103222014',
        'The World': 'https://static.wikia.nocookie.net/cyberpunk/images/a/ae/TarotCard_22_TheWorld.png/revision/latest?cb=20210103222034'
    },
    'Tarot': {
        'Carta 1': '',
        'Carta 2': '',
        'Carta 3': ''
    },
    'Tarot Major Arcana': {},
    'Tarot Minor Arcana': {}
}

DECK_OPTIONS = [
    SelectOption(label='Basic Playing Cards', value='Basic Playing Cards'),
    SelectOption(label='Tarot', value='Tarot'),
    SelectOption(label='Tarot Major Arcana', value='Tarot Major Arcana'),
    SelectOption(label='Tarot Minor Arcana', value='Tarot Minor Arcana'),
    SelectOption(label='Cyberpunk Tarot', value='Cyberpunk Tarot')
]
